// Generated by Wrangler by running `wrangler types src/env-worker.d.ts --env-interface=WorkerEnv`

interface WorkerEnv {
  AUTH: KVNamespace;
  FLICKR_API_KEY: '473ab0d04f8679aa8aa4808d77c0ca48';
  TUMBLR_OAUTH_CONSUMER_KEY: '7dHAV9lvFXd5Q1MATKPZxRRAQdHTCDfVam9OUK4hcuzomOYEPA';
  TUMBLR_OAUTH_CONSUMER_SECRET: string;
  FLICKR_API_SECRET: string;
  ASSETS: Fetcher;
}
